version: '3.8'
services:
  mysql:
    container_name: studydojo-soap-service-db
    image: mysql:latest
    ports:
      - "3300:3300"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_SOAP}
      MYSQL_DATABASE: ${MYSQL_DATABASE_SOAP}
    volumes:
      - ./db_data:/var/lib/mysql
  soap-service:
    container_name: studydojo-soap-service-api
    image: sabun:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    volumes:
      - ./target/SOAP-0.0-jar-with-dependencies.jar:/app/SOAP-0.0-jar-with-dependencies.jar
